### ISSUE TITLE
[0.0.5] バグ等の報告

### ISSUE THREAD

**Issue by nea-c** [masteralice3104/aviutl_Plugin_Update_Checker#2]
## 想定されていないであろう挙動を見せた箇所
* `エスケープしたスラッシュ`とあるが一度起動する(書き換えが起こる)とエスケープ部分が消える
* ワイルドカードを利用できるような記述がなされているが動作しない

## 気になった箇所
* 利用していないのにcheck.jsonにもsetting.jsonにもある`"ver":`　(作者用の判別要素的な？)　

## 動作環境
Windows 11 Pro / version 21H2 / OS Build 22000.675

**Comment by masteralice3104** [comment]
> ## 想定されていないであろう挙動を見せた箇所
> * `エスケープしたスラッシュ`とあるが一度起動する(書き換えが起こる)とエスケープ部分が消える
> * ワイルドカードを利用できるような記述がなされているが動作しない

バグです。
フォルダごとコピーできる想定で作っていましたがきちんと動作していませんでした。
おそらくこのソフト自体の自動アップデートが表面上だけしかできなくなっている可能性が高いです。

> ## 気になった箇所
> * 利用していないのにcheck.jsonにもsetting.jsonにもある`"ver":`　(作者用の判別要素的な？)
現在判別要素止まりですが、破壊的変更が加わった際にここのverを見て警告を出す予定です。

**Comment by nea-c** [comment]
ありがとうございます。
アップデート全裸待機します。

**Comment by nea-c** [comment]
a0.0.8cのpre-releaseあった...デバッグします
