### ISSUE TITLE
[a0.0.8c] バグ等の報告

### ISSUE THREAD

**Issue by nea-c** [masteralice3104/aviutl_Plugin_Update_Checker#3]
## 原因までわかったバグ

* 102行目の`(DLURLGet -URL $plugin_object.releases)`のリンクが`$URL`じゃないので、`"type":"tags"`でも`releases`のデータをもらいに行っちゃう

## こうしたほうがいいかもという案
* `.git`フォルダをコピーしないようにする
* check.jsonの`"tags":"<LINK>"`,`"releases":"<LINK>"`で分けて書くのではなく、`"link":"<LINK>"`のように一律にして`"type":""`を検知して勝手に分岐処理するようにする。
* 162～172行目にかけての処理。"releases"であることがデフォルトなら、"releases"をelseで処理するようにしてしまう
```ps1
162        if($plugin_object.type -eq "tags"){
166            $Latest_tag_list = TagGet2 -URL $plugin_object.tags
167            $Latest_tag_name =$Latest_tag_list[1]
168            $DLpageURL = Tags_URL -TagsPageURL $plugin_object.tags
169        }else{
170            $Latest_tag_name = TagGet -URL $plugin_object.releases
171            $DLpageURL = $plugin_object.releases
172        }
```
#### ※ pullリクエストとか出していいのかわからんので一旦こうします

**Comment by masteralice3104** [comment]
> ## 原因までわかったバグ
> * 102行目の`(DLURLGet -URL $plugin_object.releases)`のリンクが`$URL`じゃないので、`"type":"tags"`でも`releases`のデータをもらいに行っちゃう
> ## こうしたほうがいいかもという案
> * 162～172行目にかけての処理。"releases"であることがデフォルトなら、"releases"をelseで処理するようにしてしまう
> 
> ```powershell
> 162        if($plugin_object.type -eq "tags"){
> 166            $Latest_tag_list = TagGet2 -URL $plugin_object.tags
> 167            $Latest_tag_name =$Latest_tag_list[1]
> 168            $DLpageURL = Tags_URL -TagsPageURL $plugin_object.tags
> 169        }else{
> 170            $Latest_tag_name = TagGet -URL $plugin_object.releases
> 171            $DLpageURL = $plugin_object.releases
> 172        }
> ```

ありがとうございます！修正に入れておきます！


 
> * `.git`フォルダをコピーしないようにするか、リリースしているデータから削除する

~~あっ！ポンコツっぷりを発揮した~~隠しフォルダの存在忘れていました
git初心者なのがバレましたね……
次のリリースから消します……

> * check.jsonの`"tags":"<LINK>"`,`"releases":"<LINK>"`で分けて書くのではなく、`"link":"<LINK>"`のように一律にして`"type":""`を検知して勝手に分岐処理するようにする。

あえてtagsとreleasesで分けてたんですけど、実際プロジェクトのトップページのアドレスに/releases/latestか/tagsつけるだけですもんね……
また互換切りになりますが~~非安定版なので許してもらえると信じて~~今のうちにまとめておいても良いかもしれません！採用見込み！です！

> #### ※ pullリクエストとか出していいのかわからんので一旦こうします
pullリクエストはどこまで対応できるかわからないですが、私の~~ぽんこつな~~頭で理解できる内容のコードであればぜひお願いします！
