### ISSUE TITLE
[a0.0.9a] 自身のアップデートの際にcheck.jsonのtag_nameが書き換わらない

### ISSUE THREAD

**Issue by nea-c** [masteralice3104/aviutl_Plugin_Update_Checker#4]
228行目をif文の外に出したらできた...？(想定と合ってるかは不明)

**Comment by masteralice3104** [comment]
# 例外処理
    # 自身をアップデートする前にかならずjsonのバックアップをとる
    if ($URL_latest -like $this_app){
        # タグ名を更新
        $plugin_object.tag_name = $Latest_tag_name

        # 保存
        ConvertTo-Json -InputObject $JsonContent -Depth 32 | Out-File "./check.json.bak" -Encoding utf8
        ConvertTo-Json -InputObject $SettingJson -Depth 32 | Out-File "./setting.json.bak" -Encoding utf8
    }

 アプデ前のバックアップを取る際に、tag_nameを保存してからバックアップすることとしました！

**Comment by masteralice3104** [comment]
https://github.com/masteralice3104/aviutl_Plugin_Update_Checker/releases/tag/a0.0.9b
反映しています

**Comment by nea-c** [comment]
ありがとうございます！
