### ISSUE TITLE
ファイル直貼りの場合コピー時にエラーが出てしまう

### ISSUE THREAD

**Issue by yak9909** [masteralice3104/aviutl_Plugin_Update_Checker#5]
.auf など、ファイルがzipファイルではなく直で貼られているものをダウンロードさせると、
コピーする時に `Copy-Item : Cannot find path '...' because it does not exist.` というエラーが発生します

**Comment by masteralice3104** [comment]
https://github.com/masteralice3104/aviutl_Plugin_Update_Checker/releases/tag/a0.0.10a
対処しました。

直ったか確認したいので、これが発生した"link":の項目のURLを教えていただきたいです！

**Comment by yak9909** [comment]
> 直ったか確認したいので、これが発生した"link":の項目のURLを教えていただきたいです！

https://github.com/kumrnm/aviutl-authentic-grouping
このプラグインです！

アップデートを確認したので、試しに実行してみたところ今度はこのようなエラーが出ました…
`New-Object : Exception calling ".ctor" with "3" argument(s): "End of Central Directory record could not be found."`

一応、 check.json の中身を記載しておきます

check.json
```json
{
   "name":  "真・グループ制御",
   "use":  true,
   "link":  "https://github.com/kumrnm/aviutl-authentic-grouping",
   "tag_name":  null,
   "type":  "tag",
   "update_block":  false,
   "copy_folder":  "..\\plugins\\",
   "copy_file":  [
                     "authentic_grouping.auf"
                 ]
}
```

**Comment by yak9909** [comment]
> "format": "direct" の項目を追加してください。

追加したら問題なくダウンロードできました！
ちゃんと説明見てなくて申し訳ないです…
解決したのでcloseします.
